openapi: 3.0.0
info:
  title: Maintence Service Agreement
  description: Document Maintence Service Agreement API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5001/final-project-effaf/us-central1
paths:
  /users:
    get:
      summary: Retrieve a list of users
      description: Retrieves a list of users from the system.
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The user's ID.
                    username:
                      type: string
                      description: The user's username.
    post:
      summary: Create a new user
      description: Creates a new user in the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user.
                email:
                  type: string
                  format: email
                  description: The email address of the user.
      responses:
        '201':
          description: The newly created user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user's ID.
                  username:
                    type: string
                    description: The user's username.
                  email:
                    type: string
                    format: email
                    description: The user's email address.